### ISSUE TITLE
34页 缩进错误

### ISSUE THREAD

**Issue by XinArkh** [Krasjet/quaternion#10]
![Snipaste_2019-07-29_12-09-44](https://user-images.githubusercontent.com/25299977/62023282-c2d61700-b202-11e9-853e-504b2260be99.jpg)

**Comment by XinArkh** [comment]
顺便想了解一下，这篇教程是用什么工具写作完成的呢，谢谢~

**Comment by Krasjet** [comment]
用的是 LaTeX（准确说是 XeLaTeX），图什么的都是用 tikz 慢慢画出来的。
