### ISSUE TITLE
43页 概念疑似错误

### ISSUE THREAD

**Issue by XinArkh** [Krasjet/quaternion#12]
![Snipaste_2019-07-30_10-45-01](https://user-images.githubusercontent.com/25299977/62096713-320d4300-b2b7-11e9-91ec-6bab6d70894e.jpg)

![IMG_0067](https://user-images.githubusercontent.com/25299977/62097208-abf1fc00-b2b8-11e9-9fa9-2c18f3c9b733.PNG)

从速度三角形上来看，沿直线(v0v1)的速度固定，在vt=0~0.5的过程中，合速度大小应该是逐渐减小的，后半段同理是逐渐加速的。如果以上理解没有问题的话，教程中这部分应该是搞反了。

**Comment by Krasjet** [comment]
nlerp的时候**沿着v0v1这条线**（弦）移动的速度是均匀的，也就是说1、2、3分割出来的其实是相等的三段（如果它们间隔时间一样的话）。然而如果你将这三个向量延长到弧面的时候你会发现他们对应的弧长是逐渐增加的。

这里其实有一个动画：https://github.com/Krasjet/quaternion/tree/master/demo/slerp_vec#%E5%A4%A7%E8%A7%92%E5%BA%A6nlerp

**Comment by XinArkh** [comment]
明白了，是我搞错了😂
