### ISSUE TITLE
您好，我有一疑问，5.4节中双倍覆盖带来的问题，q1和-q1是同一个向量而图示中-q1和q1却是相反的向量，这样是不是有问题？应该描述为一个小于180度的角度和大于180度的角度是吗？

### ISSUE THREAD

**Issue by mantangL** [Krasjet/quaternion#14]
另p45中最下面公式，q0和q1的夹角是否应为$2\theta$呢？

**Comment by Krasjet** [comment]
q1 和 -q1 是同一个（4D）向量 ✗
q1 和 -q1 所作出的旋转变换是等价的 ✔

q0 和 q1 （作为4D向量）的夹角是 2θ ✗
q0 和 q1 对同一个向量 v 作出旋转变换之后所得的向量 v0 和 v1 之间的夹角是 2θ ✔
