### ISSUE TITLE
7.3二重四元数是否能表示缩放

### ISSUE THREAD

**Issue by gdgd8760** [Krasjet/quaternion#15]
7.3在介绍二重四元数的时候有一句话，“除了普通的四元数之外，几何代数中还衍生出来了一个二重四元数(Dual Quater- nion).它不仅能够表示 3D 旋转，还能够表示平移和缩放”。
简单看了一些文档，用了glMatrix.js库做了简单实践，发现二重四元数并没有针对单轴缩放的能力，是否我没有找到正确的使用方法呢：）
另外，基于四元数插值的能力，二重四元数如果能整合旋转、平移、缩放为一体，在实践中应该是个蛮有用的技术，希望能多讲一讲，谢谢🙏

**Comment by Krasjet** [comment]
不好意思，不知道为啥一直没收到通知/w\。Dual quaternion只能用来表达3D空间中的rigid motion，所以并不包括non-uniform scaling。当时指的是dual quaternion作为标量的时候很显然能够缩放一个向量的长度。

如果需要表示non-uniform scaling的话则需要用到不同Clifford algebra。可以看下[这篇paper](https://arxiv.org/pdf/1908.08110.pdf)的第1节和第5.5节。
