### ISSUE TITLE
两个小笔误

### ISSUE THREAD

**Issue by shuyong** [Krasjet/quaternion#18]
1) “附录 1:四元数的指数映射”，p63
展开RHS的时候，sin(theta)的展开式复制了cos(theta)的展开式，没有改过来。

2) 文中提到的“Graßmann 积”是不是“Grassmann 积”？在网上我没有查到前者，查到了后者。

**Comment by Krasjet** [comment]
ß (eszett) 是 ss 的合字 (ligature)，一般只有在不支持UTF-8的时候才会用 ss 代替。见 [Hermann Graßmann](https://de.wikipedia.org/wiki/Hermann_Gra%C3%9Fmann)。
