### ISSUE TITLE
关于 "3.1.6 Graßmann 积” 的一些愚见

### ISSUE THREAD

**Issue by Guang1234567** [Krasjet/quaternion#20]
Hello krasjet:

谢谢,你的教程. 

 但关于"3.1.6 Graßmann 积” 有一些愚见.
如下图这样子讲解, 初学者可能会更容易理解一点:

![WX20200410-165722](https://user-images.githubusercontent.com/8240718/78978730-efda1800-7b4c-11ea-8013-99d849ae93f0.png)

**Comment by Guang1234567** [comment]
另外, 请教个问题:  下图这个是从什么角度看出来的?  我想了半天没想懂

<img width="719" alt="2222" src="https://user-images.githubusercontent.com/8240718/78979040-9e7e5880-7b4d-11ea-904a-5d2d2e29e631.png">

**Comment by Krasjet** [comment]
回来有时间再研究怎么画框框_(:з」∠)_。

> 另外, 请教个问题: 下图这个是从什么角度看出来的? 我想了半天没想懂

这个只是 cross product 的一个 mnemonic（见 [Wikipedia](https://en.wikipedia.org/wiki/Cross_product#Matrix_notation)），好像这是一般微积分课里的定义方式。我个人其实更喜欢 skew-symmetric matrix 的 formulation （[Wikipedia](https://en.wikipedia.org/wiki/Cross_product#Conversion_to_matrix_multiplication)）。

**Comment by Guang1234567** [comment]
thanks.
