### ISSUE TITLE
请问文中的插图用什么画的？

### ISSUE THREAD

**Issue by itfanr** [Krasjet/quaternion#21]
看起来插图都不是图片，请问怎么制作的？谢谢

**Comment by Krasjet** [comment]
用的是 [PGF/TikZ](http://ctan.math.utah.edu/ctan/tex-archive/graphics/pgf/base/doc/pgfmanual.pdf)。

这个绘图系统的复杂性可能有点大，所以可能不是适合任何人。[Inkscape](https://inkscape.org/) 输出 eps 可能也是很好的选择。

**Comment by itfanr** [comment]
@Krasjet  我在其他QQ群问了。果然是用的tikz，都说学习曲线陡峭。感谢啊！我看看eps
