### ISSUE TITLE
29页Lemma2，v∥不是纯四元数也行吧？

### ISSUE THREAD

**Issue by Aquapisces** [Krasjet/quaternion#25]
首先阅读这本书真是非常感动愉快的体验，作者真的是用心了，太伟大了！
其次如标题所述，29页的Lemma2中，v∥是纯四元数似乎是多余的限制？如果是，不妨删掉
再次感谢作者^_^

**Comment by Krasjet** [comment]
这里的 v_∥ 更多的是指一个向量，这个 lemma 的意思其实是 q 这个四元数对 v_∥ 这个向量所作出变换与左乘和右乘无关。

如果换成更通用的版本的话，就没有办法区分向量和变换，做出以上的解读了，这样反而会更让人困惑。有时候 lemma 并不需要找到最通用的版本，在这个情况下只会增加证明的难度，没有给我们提供更多有用的信息。
