### ISSUE TITLE
Quaternion 2.3节中的问题

### ISSUE THREAD

**Issue by Mud-B** [Krasjet/quaternion#30]
这个等式的第二行是怎么推出来的，能否细讲下或给个Reference，我代数没啥基础
```
v′⊥=v′𝑣+v′𝑤
   =cos(θ)v⊥+sin(θ)w
   =cos(θ)v⊥+sin(θ)(u×v⊥)
```

**Comment by Krasjet** [comment]
这个是很常用的[投影公式](https://en.wikipedia.org/wiki/Vector_projection)
```
project v onto u
projᵤv = (⟨u,v⟩/⟨u,u⟩)u
```
你也可以直接算出来

```
cos(θ) = 临边/斜边 = ∥v⟂'∥ / ∥vᵥ'∥ = ∥v⟂∥ / ∥vᵥ'∥
⇒ ∥vᵥ'∥ = ∥v⟂∥cos(θ)
⇒ vᵥ' = ∥vᵥ'∥ (v⟂/∥v⟂∥ )
       = (∥v⟂∥cos(θ)) (v⟂/∥v⟂∥ )
       = cos(θ)v⟂
```

**Comment by Mud-B** [comment]
原来是这么回事，我懂了。
感谢Krasjet！



---Original---
From: ***@***.***&gt;
Sent at: 2021年9月10日(Fri) Early Morning0:56
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Krasjet/quaternion] Quaternion 2.3节中的问题 (#30)




 
这个是很常用的投影公式
 project v onto u projᵤv = (⟨u,v⟩/⟨u,u⟩)u  
你也可以直接算出来
 cos(θ) = 临边/斜边 = ∥v⟂'∥ / ∥vᵥ'∥ = ∥v⟂∥ / ∥vᵥ'∥ ⇒ ∥vᵥ'∥ = ∥v⟂∥cos(θ) ⇒ vᵥ' = ∥vᵥ'∥ (v⟂/∥v⟂∥ )        = (∥v⟂∥cos(θ)) (v⟂/∥v⟂∥ )        = cos(θ)v⟂
