### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by zhongxiang117** [Krasjet/quaternion#32]
四元树文档，第18页，3.1.4节：

> 如果是 𝑞1𝑞2，那么我们就说「𝑞2 左乘以 𝑞1」，如果是 𝑞2𝑞1，那我们就说「𝑞2 右乘以 𝑞1」．

左右乘的顺序是不是写反了？

**Comment by Krasjet** [comment]
这个是正确的。你可以理解为“在q2的左边乘上q1”，“在q2的右边乘上q1”。

**Comment by zhongxiang117** [comment]
如果可以这样理解的话，那全文就有些混乱 “左右” 不分了。

比如说就在它下一页，第 19 页：

> ijk = -1
> iijk = -i  (等式两边同时**左乘以**i）

下面语句（同一页）：

> ijk = -1
> ijkk = -k (等式两边同时**右乘以**k）

第20页末尾：

> q1q2 = ''Matrix"
> 注意，这个矩阵所做出的变换等价于**左乘** 𝑞1．因为四元数不符合交换律，所以**右乘** 𝑞1 的变换是一个不同的矩阵

如果你要是严格区分 “乘” 和 “乘以” 的不同也可以，但是全文的行文，明显是 “乘” 和 “乘以” 表示同一个意思的。

麻烦您再读一读您写的文章，就这个有问题。
