### ISSUE TITLE
3.1.4 四元数乘法 左乘和右乘的定义是否写反了？

### ISSUE THREAD

**Issue by exitNA** [Krasjet/quaternion#35]
> 如果是 𝑞1𝑞2，那么我们就说「𝑞2 左乘以 𝑞1」，如果是 𝑞2𝑞1，那我们就说「𝑞2 右乘以 𝑞1」．

这里𝑞1𝑞2 是否应该为「𝑞2 右乘以 𝑞1」 ？

**Comment by Krasjet** [comment]
see #32
